# Generated by Django 5.0 on 2024-01-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('appearance', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StylePreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artStyle', models.CharField(max_length=100)),
                ('composition', models.CharField(max_length=100)),
                ('lighting', models.CharField(max_length=100)),
                ('aspectRatio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalText', models.TextField()),
                ('userUploads', models.TextField()),
                ('specificRequests', models.TextField()),
                ('feedbackLoop', models.TextField()),
                ('templates', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('emotionTone', models.CharField(max_length=50)),
                ('emotionalIntensity', models.IntegerField()),
                ('geographicalContext', models.CharField(max_length=100)),
                ('temporalContext', models.CharField(max_length=100)),
                ('sourceCredibility', models.IntegerField()),
                ('audienceAgeGroup', models.CharField(max_length=50)),
                ('audienceInterests', models.TextField()),
                ('keywords', models.ManyToManyField(to='image_generator.keyword')),
                ('subcategories', models.ManyToManyField(to='image_generator.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='VisualElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainSubject', models.CharField(max_length=255)),
                ('backgroundScene', models.CharField(max_length=100)),
                ('colorPalette', models.CharField(max_length=100)),
                ('texture', models.CharField(max_length=100)),
                ('dynamicElements', models.TextField()),
                ('textOverlayStyle', models.TextField()),
                ('motionEffects', models.TextField()),
                ('characters', models.ManyToManyField(to='image_generator.character')),
                ('objects', models.ManyToManyField(to='image_generator.objectdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ImageGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_context', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_generator.newscontext')),
                ('style_preferences', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_generator.stylepreferences')),
                ('user_customizations', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_generator.usercustomizations')),
                ('visual_elements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='image_generator.visualelements')),
            ],
        ),
    ]
