# Generated by Django 4.2.7 on 2024-01-29 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_voiceupload_transcript"),
        ("image_generator", "0002_rename_objects_visualelements_object_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagegeneration",
            name="image_upload",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.imageupload",
            ),
        ),
        migrations.AddField(
            model_name="imagegeneration",
            name="text_upload",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.textupload",
            ),
        ),
        migrations.AlterField(
            model_name="usercustomizations",
            name="additionalText",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="usercustomizations",
            name="feedbackLoop",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="usercustomizations",
            name="specificRequests",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="usercustomizations",
            name="templates",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="usercustomizations",
            name="userUploads",
            field=models.TextField(blank=True),
        ),
    ]
