# Generated by Django 4.2.7 on 2024-01-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0003_imagegeneration_image_upload_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="generated_images/")),
            ],
        ),
    ]
