# Generated by Django 4.2.7 on 2024-01-30 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0004_generatedimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimages",
            name="image_generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_images",
                to="image_generator.imagegeneration",
            ),
        ),
    ]
