# Generated by Django 4.2.7 on 2024-02-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0005_generatedimages_image_generation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stylepreferences",
            name="artStyle",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="stylepreferences",
            name="aspectRatio",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="stylepreferences",
            name="composition",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="stylepreferences",
            name="lighting",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="visualelements",
            name="backgroundScene",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="visualelements",
            name="colorPalette",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="visualelements",
            name="dynamicElements",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="visualelements",
            name="mainSubject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="visualelements",
            name="textOverlayStyle",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="visualelements",
            name="texture",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
