# Generated by Django 5.0 on 2024-01-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_models_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalmetadata',
            name='audience',
            field=models.ManyToManyField(blank=True, related_name='additional_metadata_audience', to='meta_models_management.audience'),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='content_themes',
            field=models.ManyToManyField(blank=True, related_name='additional_metadata_content_themes', to='meta_models_management.contenttheme'),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='geographic_relevance',
            field=models.ManyToManyField(blank=True, related_name='additional_metadata_geographic_relevance', to='meta_models_management.geographicrelevance'),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='influencer_tags',
            field=models.ManyToManyField(blank=True, related_name='additional_metadata_influencer_tags', to='meta_models_management.influencertag'),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='sentiment_trends',
            field=models.ManyToManyField(blank=True, related_name='additional_metadata_sentiment_trends', to='meta_models_management.sentimenttrend'),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='source_attributes',
            field=models.ManyToManyField(blank=True, related_name='additional_metadata_source_attributes', to='meta_models_management.sourceattribute'),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='technical_level',
            field=models.ManyToManyField(blank=True, related_name='additional_metadata_technical_level', to='meta_models_management.technicallevel'),
        ),
        migrations.AlterField(
            model_name='additionalmetadata',
            name='temporal_relevance',
            field=models.ManyToManyField(blank=True, related_name='additional_metadata_temporal_relevance', to='meta_models_management.temporalrelevance'),
        ),
        migrations.AlterField(
            model_name='inputrecord',
            name='input_id',
            field=models.CharField(max_length=400),
        ),
    ]
