# Generated by Django 5.0 on 2023-12-29 14:48

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voiceupload",
            name="voice_file",
            field=models.FileField(
                upload_to="voices/", validators=[api.validators.validate_file_extension]
            ),
        ),
    ]
