# Generated by Django 5.0 on 2024-01-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_voiceupload_voice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceupload',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
