# Generated by Django 4.2.7 on 2024-01-30 07:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_voiceupload_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageupload",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="textupload",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
